# See README.md for plugin installation

"$schema" = "https://yazi-rs.github.io/schemas/yazi.json"

[manager]
show_hidden    = true
# mouse_events   = [ ] # disable mouse support; might be useful when copying text with Ctrl + shift + v. Holding "Shift" while selecting also works.

# Below uses git plugin:
# $ ya pack -a yazi-rs/plugins:git
# ~/.config/yazi/plugins/git.yazi/README.md (unix)

[[plugin.prepend_fetchers]]
id   = "git"
name = "*"
run  = "git"

[[plugin.prepend_fetchers]]
id   = "git"
name = "*/"
run  = "git"

