live_config_reload = false

[colors.primary]
background = "#000000"

[cursor.style]
shape = "Underline"

[font]
size = 11.0

[font.bold]
family = "Mononoki Nerd Font Propo"
style = "Bold"

[font.bold_italic]
family = "Mononoki Nerd Font Propo"
style = "Bold Italic"

[font.italic]
family = "Mononoki Nerd Font Propo"
style = "Italic"

[font.normal]
family = "Mononoki Nerd Font Propo"
style = "Regular"

[keyboard]
bindings = [
{ key = "Key0",    mods = "Control", action = "ResetFontSize" },
{ key = "Equals",  mods = "Control", action = "IncreaseFontSize" },
{ key = "Minus",   mods = "Control", action = "DecreaseFontSize" },
{ key = "Q",       mods = "Control", action = "Quit" },
{ key = "T",  mods = "Control|Shift", action = "CreateNewWindow" },
]

[scrolling]
multiplier = 6

[window]
decorations = "none"
dynamic_title = true
opacity = 0.8 # In X11: Requires a compositor
resize_increments = true
startup_mode = "Maximized"
